-- Nexora Studios inquiry storage
-- Run this in the Supabase SQL Editor before enabling the website form.

create table if not exists public.inquiries (
  id integer generated by default as identity primary key,
  business_name text not null,
  contact_name text not null,
  email text not null,
  phone text,
  website text,
  project_type text not null,
  project_reason text not null,
  referral_source text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists inquiries_created_at_idx
  on public.inquiries (created_at desc);

create index if not exists inquiries_email_idx
  on public.inquiries (email);

alter table public.inquiries enable row level security;

-- The website writes through the API server using the Supabase service-role key.
-- Do not expose that key in browser code. No anonymous read/write policy is added.